
//
// This file has been generated by the Cornerstone file generator.
//
// PLEASE, DO NOT EDIT IT MANUALLY
//

#pragma once

#include "CoreMinimal.h"
#include "Conduit.h"
#include "GenUtils.h"
#include "RpcClient.h"
#include "Search.generated.h"


// Enums:
// Structures:
USTRUCT(BlueprintType, meta=(DisplayName="Search SearchRequest"))
struct MOXCLIENT_API FSearch_SearchRequest
{
    GENERATED_USTRUCT_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY(BlueprintReadWrite, Transient)
    FString Query;

    UPROPERTY(BlueprintReadWrite, Transient)
    int32 PageNumber;

    UPROPERTY(BlueprintReadWrite, Transient)
    int32 ResultPerPage;
};

USTRUCT(BlueprintType, meta=(DisplayName="Search SearchResponse"))
struct MOXCLIENT_API FSearch_SearchResponse
{
    GENERATED_USTRUCT_BODY()

public:
    // Conduits and GRPC stub
    UPROPERTY(BlueprintReadWrite, Transient)
    FString Result;
};

// Forward class definitions (for delegates)
class UGreeterServiceRpcClient;

// Dispatcher delegates
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FEventSearchGreeterService, UGreeterServiceRpcClient*, RpcClient, const FSearch_SearchResponse&, Response, FGrpcStatus, Status);

UCLASS()
class MOXCLIENT_API UGreeterServiceRpcClient : public URpcClient
{
    GENERATED_BODY()

public:
    // Conduits and GRPC stub
    TConduit<TRequestWithContext<FSearch_SearchRequest>, TResponseWithStatus<FSearch_SearchResponse>> SearchConduit;

    UPROPERTY(BlueprintAssignable, Category="MOX|RPC Responses|GreeterService")
    FEventSearchGreeterService EventSearch;


    // Methods
    void HierarchicalInit() override;

    void HierarchicalUpdate() override;

    UFUNCTION(BlueprintCallable, Category="MOX|RPC Requests|GreeterService")
    bool Search(FSearch_SearchRequest Request, const FGrpcClientContext& Context);
};


