
//
// This file has been generated by the Cornerstone file generator.
//
// PLEASE, DO NOT EDIT IT MANUALLY
//

#pragma once

#include "CastUtils.h"
#include "GrpcIncludesBegin.h"
#include "Wrappers/search.pb.h"
#include "Wrappers/search.grpc.pb.h"
#include "GrpcIncludesEnd.h"
#include "search/Search.h"

namespace casts
{
    template <>
    FORCEINLINE FSearch_SearchRequest Proto_Cast(const SearchRequest& InItem)
    {
        FSearch_SearchRequest OutItem;

        // FSearch_SearchRequest::Query <- SearchRequest::query
        // Struct (FString) <- Struct (std::string)
        OutItem.Query = Proto_Cast<FString>(InItem.query());

        // FSearch_SearchRequest::PageNumber <- SearchRequest::page_number
        // Primitive (int32) <- Primitive (google::protobuf::int32)
        OutItem.PageNumber = Proto_Cast<int32>(InItem.page_number());

        // FSearch_SearchRequest::ResultPerPage <- SearchRequest::result_per_page
        // Primitive (int32) <- Primitive (google::protobuf::int32)
        OutItem.ResultPerPage = Proto_Cast<int32>(InItem.result_per_page());

        return OutItem;
    }

    template <>
    FORCEINLINE SearchRequest Proto_Cast(const FSearch_SearchRequest& InItem)
    {
        SearchRequest OutItem;

        // SearchRequest::query <- FSearch_SearchRequest::Query
        // Struct (std::string) <- Struct (FString)
        OutItem.set_query(Proto_Cast<std::string>(InItem.Query));

        // SearchRequest::page_number <- FSearch_SearchRequest::PageNumber
        // Primitive (google::protobuf::int32) <- Primitive (int32)
        OutItem.set_page_number(Proto_Cast<google::protobuf::int32>(InItem.PageNumber));

        // SearchRequest::result_per_page <- FSearch_SearchRequest::ResultPerPage
        // Primitive (google::protobuf::int32) <- Primitive (int32)
        OutItem.set_result_per_page(Proto_Cast<google::protobuf::int32>(InItem.ResultPerPage));

        return OutItem;
    }

    template <>
    FORCEINLINE FSearch_SearchResponse Proto_Cast(const SearchResponse& InItem)
    {
        FSearch_SearchResponse OutItem;

        // FSearch_SearchResponse::Result <- SearchResponse::result
        // Struct (FString) <- Struct (std::string)
        OutItem.Result = Proto_Cast<FString>(InItem.result());

        return OutItem;
    }

    template <>
    FORCEINLINE SearchResponse Proto_Cast(const FSearch_SearchResponse& InItem)
    {
        SearchResponse OutItem;

        // SearchResponse::result <- FSearch_SearchResponse::Result
        // Struct (std::string) <- Struct (FString)
        OutItem.set_result(Proto_Cast<std::string>(InItem.Result));

        return OutItem;
    }

}// end namespace 'casts'


